package com.example.recyclerapplication

class FakeDataFactory {

    fun getItems(): List<ItemData> {

        return listOf(
            ItemData(title = "1", isChecked = false),
            ItemData(title = "2", isChecked = false),
            ItemData(title = "3", isChecked = false),
            ItemData(title = "4", isChecked = false),
            ItemData(title = "5", isChecked = false),
            ItemData(title = "6", isChecked = false),
            ItemData(title = "1", isChecked = false),
            ItemData(title = "2", isChecked = false),
            ItemData(title = "3", isChecked = false),
            ItemData(title = "4", isChecked = false),
            ItemData(title = "5", isChecked = false),
            ItemData(title = "6", isChecked = false),
            ItemData(title = "1", isChecked = false),
            ItemData(title = "2", isChecked = false),
            ItemData(title = "3", isChecked = false),
            ItemData(title = "4", isChecked = false),
            ItemData(title = "5", isChecked = false),
            ItemData(title = "6", isChecked = false),
            ItemData(title = "1", isChecked = false),
            ItemData(title = "2", isChecked = false),
            ItemData(title = "3", isChecked = false),
            ItemData(title = "4", isChecked = false),
            ItemData(title = "5", isChecked = false),
            ItemData(title = "6", isChecked = false),
            ItemData(title = "1", isChecked = false),
            ItemData(title = "2", isChecked = false),
            ItemData(title = "3", isChecked = false),
            ItemData(title = "4", isChecked = false),
            ItemData(title = "5", isChecked = false),
            ItemData(title = "6", isChecked = false),
            ItemData(title = "1", isChecked = false),
            ItemData(title = "2", isChecked = false),
            ItemData(title = "3", isChecked = false),
            ItemData(title = "4", isChecked = false),
            ItemData(title = "5", isChecked = false),
            ItemData(title = "6", isChecked = false),
            ItemData(title = "1", isChecked = false),
            ItemData(title = "2", isChecked = false),
            ItemData(title = "3", isChecked = false),
            ItemData(title = "4", isChecked = false),
            ItemData(title = "5", isChecked = false),
            ItemData(title = "6", isChecked = false),
            ItemData(title = "1", isChecked = false),
            ItemData(title = "2", isChecked = false),
            ItemData(title = "3", isChecked = false),
            ItemData(title = "4", isChecked = false),
            ItemData(title = "5", isChecked = false),
            ItemData(title = "6", isChecked = false),
            ItemData(title = "1", isChecked = false),
            ItemData(title = "2", isChecked = false),
            ItemData(title = "3", isChecked = false),
            ItemData(title = "4", isChecked = false),
            ItemData(title = "5", isChecked = false),
            ItemData(title = "6", isChecked = false),
            ItemData(title = "1", isChecked = false),
            ItemData(title = "2", isChecked = false),
            ItemData(title = "3", isChecked = false),
            ItemData(title = "4", isChecked = false),
            ItemData(title = "5", isChecked = false),
            ItemData(title = "6", isChecked = false),
        )
    }
}